# Generated by Django 5.2.14 on 2026-05-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_user_id_task_user_alter_task_description'),
    ]

    operations = [
        # First drop the existing DurationField
        migrations.RemoveField(
            model_name='task',
            name='time_spent',
        ),
        # Then add it back as IntegerField
        migrations.AddField(
            model_name='task',
            name='time_spent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
