# Generated by Django 5.2.14 on 2026-05-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Fitness', 'Fitness'), ('Study', 'Study'), ('Mindfulness', 'Mindfulness'), ('Finance', 'Finance'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
