# Generated by Django 5.2.14 on 2026-05-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='best_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
